package com.zhr.test.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhr.test.Scale;

import com.zhr.test.dao.ScaleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scaleDaoConfig;

    private final ScaleDao scaleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scaleDaoConfig = daoConfigMap.get(ScaleDao.class).clone();
        scaleDaoConfig.initIdentityScope(type);

        scaleDao = new ScaleDao(scaleDaoConfig, this);

        registerDao(Scale.class, scaleDao);
    }
    
    public void clear() {
        scaleDaoConfig.clearIdentityScope();
    }

    public ScaleDao getScaleDao() {
        return scaleDao;
    }

}
